version: '3'

networks: 
  neo4j-network:
    driver: bridge

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-base
    networks: 
      - neo4j-network
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/conf:/conf
    environment:
      - NEO4J_ULIMIT_NOFILE=40000
