version: '3'

networks: 
  neo4jnetwork:
    driver: bridge

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4jserver
    networks: 
      - neo4jnetwork
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/conf:/conf
      - $HOME/neo4j/ssl:/ssl
      - $HOME/neo4j/plugins:/plugins
    environment:
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"] 
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
      
